### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by nwardFoleum** [binjospookie/spacing-helper#195]
using latest version when building react based app, get an error of:

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/devop/verus.io/node_modules/spacing-helper/build/index.js
require() of ES modules is not supported.
require() of /home/devop/verus.io/node_modules/spacing-helper/build/index.js from /home/devop/verus.io/.next/server/pages/_app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/devop/verus.io/node_modules/spacing-helper/package.json.

**Comment by nwardFoleum** [comment]
I don't have the issue when using 4.1.2

**Comment by binjospookie** [comment]
Fixed in 4.1.6
